name: Generate builder image

on:
  workflow_dispatch:

env:
  REF: ${{ github.ref }}
  AUTHOR: ${{ secrets.RELEASE_USERNAME }}
  PAT: ${{ secrets.RELEASE_TOKEN }}
  ORG: Ananda-Aropa
  PREFIX: aaropa_rootfs_installer
  BRANCH: main
  WORKFLOW: extract-rootfs.yml

jobs:
  build-and-publish-image:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Trigger Workflow for BlissOS Installer
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ env.ORG }}
          repo: ${{ env.PREFIX }}_blissos
          github_token: ${{ env.PAT }}
          github_user: ${{ env.AUTHOR }}
          workflow_file_name: ${{ env.WORKFLOW }}
          ref: ${{ env.BRANCH }}
          trigger_workflow: true
          wait_workflow: false

      - name: Trigger Workflow for BassOS Installer
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ env.ORG }}
          repo: ${{ env.PREFIX }}_bass
          github_token: ${{ env.PAT }}
          github_user: ${{ env.AUTHOR }}
          workflow_file_name: ${{ env.WORKFLOW }}
          ref: ${{ env.BRANCH }}
          trigger_workflow: true
          wait_workflow: false

      - name: Trigger Workflow for LineageOS Installer
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ env.ORG }}
          repo: ${{ env.PREFIX }}_lineageos
          github_token: ${{ env.PAT }}
          github_user: ${{ env.AUTHOR }}
          workflow_file_name: ${{ env.WORKFLOW }}
          ref: ${{ env.BRANCH }}
          trigger_workflow: true
          wait_workflow: false